# linex Project
name: linex Project v1.1-ub
on:
  workflow_dispatch:
    inputs:
      ubuntu:
        description: 'Run on'
        default: 'ubuntu-latest'
        required: true
        type: string
      name:
        description: 'Name'
        default: '4.9-kernel_clang'
        required: true
        type: string
      compiler:
        description: 'Compiler | gcc|clang|llvm '
        default: 'clang'
        required: true
        type: string
      kernel-url:
        description: 'Kernel-url'
        default: 'https://github.com/linex-17/Limitless.git'
        required: true
        type: string
      kernel-branch:
        description: 'Kernel-branch'
        default: 'ten'
        required: true
        type: string
      kernel-config:
        description: 'Kernel-config'
        default: 'beryllium_defconfig'
        required: true
        type: string
      kernelsu:
        description: 'KernelSU | false if source not support'
        default: 'false'
        required: true
        type: string
      command:
        description: 'Command+'
        default: 'false'
        required: true
        type: string
      any-kernel3:
        description: 'Any-Kernel3'
        default: 'https://github.com/osm0sis/AnyKernel3'
        required: true
        type: string
        
jobs:
  linex-compiler-v1:
    runs-on: ${{ inputs.ubuntu }}
    steps:
    - name: Checkin
      run: |
         echo "run-on: ${{ inputs.ubuntu }}"
         echo "name: ${{ inputs.name }}"
         echo "compiler: ${{ inputs.compiler }}"
         echo "kernel-url: ${{ inputs.kernel-url }}"
         echo "kernel-branch: ${{ inputs.kernel-branch }}"
         echo "kernel-config: ${{ inputs.kernel-config }}"
         echo "kernelsu: ${{ inputs.kernelsu }}"
         echo "command+: ${{ inputs.command }}"
         echo "any-kernel3: ${{ inputs.any-kernel3 }}"
         echo "linex Project"
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup
      run: |
         sudo apt-get update
         sudo apt-get install --no-install-recommends -y \git curl bc bison flex make clang llvm lld gcc g++ zip python3 aria2 wget ca-certificates \ binutils binutils-aarch64-linux-gnu binutils-arm-linux-gnueabi libssl-dev libelf-dev
    - name: Setup Kernel
      run: |
         git clone --depth=1 ${{ inputs.kernel-url }} -b ${{ inputs.kernel-branch }} kernel-dir
    - name: Setup KernelSU
      run: |
         if [ ${{ inputs.kernelsu }} != false ]; then
            cd kernel-dir
            rm -rf KernelSU
            ${{ inputs.kernelsu }}
         else
            echo "KernelSU Disable"
         fi
    - name: Compile
      run: |
          mkdir -p out
          cd kernel-dir
          export KBUILD_BUILD_USER=linex
          export KBUILD_BUILD_HOST=project
          COMMAND="make -j$(nproc --all) ${{ inputs.kernel-config }} ARCH=arm64 O=../out all"
          COMMAND="$COMMAND CROSS_COMPILE=aarch64-linux-android- CROSS_COMPILE_ARM32=arm-linux-androideabi-"
          if [ "${{ inputs.compiler }}" = "clang" ]; then
          COMMAND="$COMMAND CC=clang CLANG_TRIPLE=aarch64-linux-gnu- LLVM=1 LLVM_IAS=1"
          fi
          if [ "${{ inputs.compiler }}" = "llvm" ]; then
          COMMAND="$COMMAND CC=clang LLVM=1 LLVM_IAS=0 AR=llvm-ar NM=llvm-nm STRIP=llvm-strip OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump READELF=llvm-readelf HOSTCC=clang HOSTCXX=clang++ HOSTAR=llvm-ar"
          fi
          if [ "${{ inputs.command }}" != "false" ]; then
          COMMAND="$COMMAND ${{ inputs.command }}"
          fi
          eval $COMMAND
    - name: AnyKernel3
      run: |
          git clone ${{ inputs.any-kernel3 }} AnyKernel3
          rm -rf AnyKernel3/.git AnyKernel3/.github AnyKernel3/LICENSE AnyKernel3/README.md AnyKernel3/modules AnyKernel3/patch AnyKernel3/ramdisk
          
          if [[ -f out/arch/arm64/boot/Image.gz-dtb ]]; then
            cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/Image.gz-dtb
          elif [[ -f out/arch/arm64/boot/Image-dtb ]]; then
            cp out/arch/arm64/boot/Image-dtb AnyKernel3/Image-dtb
          elif [[ -f out/arch/arm64/boot/Image.gz ]]; then
            cp out/arch/arm64/boot/Image.gz AnyKernel3/Image.gz
          elif [[ -f out/arch/arm64/boot/Image ]]; then
            cp out/arch/arm64/boot/Image AnyKernel3/Image
          fi
          if [ -f out/arch/arm64/boot/dtbo.img ]; then
            cp out/arch/arm64/boot/dtbo.img AnyKernel3/dtbo.img
          fi
    - name: Upload
      run: |
          mkdir Upload
          cp -rf AnyKernel3/* Upload
    - id: Artifact
      uses: actions/upload-artifact@v4
      with:
        name: "${{ inputs.name }}"
        path: Upload/*
    
