name: "Build Kernel Simple"

on:
  workflow_dispatch:

env:
  OUT_DIR: ${{ github.workspace }}/out
  KERNEL_NAME: kernel
  KERNEL_REPO: https://github.com/LineageOS/android_kernel_xiaomi_sdm845
  KERNEL_BRANCH: lineage-18.1
  DEFCONFIG: vendor/beryllium_defconfig

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: 📦 Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          git curl wget zip unzip \
          bc bison flex make \
          gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi \
          libssl-dev build-essential \
          python3 python-is-python3 jq

      - name: 🌟 Clone kernel
        run: |
          git clone --depth=1 --recursive \
          --branch $KERNEL_BRANCH \
          $KERNEL_REPO \
          $KERNEL_NAME

      - name: ⚙️ Setup toolchain (clang proton)
        run: |
          git clone --depth=1 https://github.com/kdrag0n/proton-clang clang

          echo "$PWD/clang/bin" >> $GITHUB_PATH

      - name: 📁 Prepare output dir
        run: mkdir -p $OUT_DIR

      - name: ⚙️ Build defconfig
        working-directory: ${{ env.KERNEL_NAME }}
        run: |
          make ARCH=arm64 O=$OUT_DIR $DEFCONFIG

      - name: 🔨 Build kernel
        working-directory: ${{ env.KERNEL_NAME }}
        run: |
          make -j$(nproc) \
          ARCH=arm64 \
          O=$OUT_DIR \
          CC=clang \
          CROSS_COMPILE=aarch64-linux-gnu- \
          CROSS_COMPILE_ARM32=arm-linux-gnueabi-

      - name: 📦 Upload Image
        uses: actions/upload-artifact@v4
        with:
          name: Image
          path: ${{ env.OUT_DIR }}/arch/arm64/boot/Image

      - name: 📦 Upload Image.gz
        uses: actions/upload-artifact@v4
        with:
          name: Image.gz
          path: ${{ env.OUT_DIR }}/arch/arm64/boot/Image.gz
