# linex Project - Customized for Poco F1 (beryllium)
# Version 3.0 Final Ultimate - Menu Choice Dropdown & Dynamic Compilation Link Fix
name: Poco F1 Kernel Compiler 3.0
on:
  workflow_dispatch:
    inputs:
      ubuntu:
        description: 'Run on'
        default: 'ubuntu-22.04'
        required: true
        type: string
      zip_name:
        description: 'Nama File ZIP Akhir'
        default: 'Silvercore'
        required: true
        type: string
      kernel_version:
        description: 'Isi angka (misal 4.19.1) atau biarkan "original" untuk versi asli'
        default: 'original'
        required: true
        type: string
      kernel_name:
        description: 'Nama Utama Kernel (Contoh: kyzuna)'
        default: 'kyzuna'
        required: true
        type: string
      rom_type:
        description: 'Tipe ROM/Tag (nse / se / dynamic)'
        default: 'nse'
        required: true
        type: string
      project_name:
        description: 'Build Project (@nama-project)'
        default: 'kyy'
        required: true
        type: string
      compiler:
        description: 'Pilih Compiler Pro'
        default: 'weebx-clang'
        required: true
        type: choice
        options:
        - aosp-clang
        - proton-clang
        - weebx-clang
        - zycromer-clang
        - sdclang
      aosp-clang-ver:
        description: 'Versi Clang (Hanya jika pakai aosp-clang)'
        default: '11'
        required: true
        type: choice
        options:
        - '11'
        - '12'
        - '13'
        - '14'
        - '15'
        - 'latest'
      gpu_min_clock:
        description: 'Frekuensi MINIMAL GPU (dalam MHz, Contoh: 180 atau 257)'
        default: '180'
        required: true
        type: string
      gpu_max_clock:
        description: 'Frekuensi MAKSIMAL GPU / OC (dalam MHz, Contoh: 710, 800, 825)'
        default: '800'
        required: true
        type: string
      kernel-url:
        description: 'Kernel Source URL'
        default: 'https://github.com/PainKiller3/android_kernel_xiaomi_sdm845.git'
        required: true
        type: string
      kernel-branch:
        description: 'Kernel Branch'
        default: 'main'
        required: true
        type: choice
        options:
        - ten
        - eleven
        - twelve
        - thirteen
      kernel-config:
        description: 'Kernel Config (Defconfig)'
        default: 'beryllium_defconfig'
        required: true
        type: choice
        options:
          - beryllium_defconfig
          - stock-beryllium_defconfig
          - sdm845_defconfig
          - sdm845-perf_defconfig
      kernelsu:
        description: 'KernelSU (ksu/next/false)'
        default: 'ksu'
        required: true
        type: choice
        options:
        - ksu
        - next
        - "false"
      disable-lto:
        description: 'Disable LTO'
        default: 'true'
        required: true
        type: string
      AK3:
        description: 'AnyKernel3 Template'
        default: 'https://github.com/osm0sis/AnyKernel3'
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.ubuntu }}
    steps:
    - name: Mempersiapkan Lingkungan Build
      run: |
         echo "Building Poco F1 Kernel Version 3.0 Pro Ultimate"
         sudo timedatectl set-timezone Asia/Jakarta

    - name: Checkout Workflow
      uses: actions/checkout@v4

    - name: ...Instalasi Paket Dependensi
      run: |
         sudo apt-get update
         sudo apt-get install --no-install-recommends -y gcc-arm-linux-gnueabi gcc-aarch64-linux-gnu lld llvm g++-aarch64-linux-gnu bc aria2 zip tar libssl-dev flex bison git git-lfs libelf-dev python3 libbio-perl libipc-cmd-perl libtinfo5
         aria2c -q https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh && NONINTERACTIVE=1 bash ./uninstall.sh -f -q

    - name: Optimasi Swap Space
      run: |
         if [ -f /bin/swapon ]; then
             export SWAP_FILE=$(swapon --show=NAME | tail -n 1)
             sudo swapoff $SWAP_FILE || true
             sudo rm $SWAP_FILE || true
             sudo fallocate -l 16G $SWAP_FILE
             sudo chmod 600 $SWAP_FILE
             sudo mkswap $SWAP_FILE
             sudo swapon $SWAP_FILE
         fi

    - name: Download Toolchains (Hybrid Setup)
      run: |
         rm -rf $HOME/tc $HOME/gcc-64 $HOME/gcc-32
         mkdir -p $HOME/tc $HOME/gcc-64 $HOME/gcc-32
         
         # GCC 4.9 Wajib untuk stabilitas kernel 4.9 lama (beryllium sdm845)
         aria2c -q -o gcc-64.tar.gz "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/0a0604336d4d1067aa1aaef8d3779b31fcee841d.tar.gz"
         tar -C $HOME/gcc-64 -zxf gcc-64.tar.gz && rm gcc-64.tar.gz
         aria2c -q -o gcc-32.tar.gz "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/4d16d93f49c2b5ecdd0f12c38d194835dd595603.tar.gz"
         tar -C $HOME/gcc-32 -zxf gcc-32.tar.gz && rm gcc-32.tar.gz
         
         # Logika Download Compiler Berdasarkan Pilihan Menu
         if [ "${{ inputs.compiler }}" = "aosp-clang" ]; then
             case "${{ inputs.aosp-clang-ver }}" in
                 11) URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/tags/android-11.0.0_r46/clang-r383902b1.tar.gz" ;;
                 12) URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/tags/android-12.1.0_r27/clang-r416183b1.tar.gz" ;;
                 13) URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/tags/android-13.0.0_r30/clang-r450784d.tar.gz" ;;
                 14) URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/tags/android-14.0.0_r15/clang-r487747c.tar.gz" ;;
                 15) URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android15-gsi/clang-r510928.tar.gz" ;;
                 *) URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r530567.tar.gz" ;;
             esac
             aria2c -q -o tc.tar.gz "$URL"
             tar -C $HOME/tc -zxf tc.tar.gz && rm tc.tar.gz
         
         elif [ "${{ inputs.compiler }}" = "proton-clang" ]; then
             echo "Downloading Proton Clang..."
             aria2c -q -o proton.tar.gz "https://github.com/kdrag0n/proton-clang/archive/refs/heads/master.tar.gz"
             tar -C $HOME/tc --strip-components=1 -zxf proton.tar.gz && rm proton.tar.gz
             rm -rf $HOME/tc/bin/ld* $HOME/tc/bin/as*
             
         elif [ "${{ inputs.compiler }}" = "weebx-clang" ]; then
             echo "Downloading Official WeebX (Yuki) Clang Tarball..."
             aria2c -q -o weebx.tar.gz "https://github.com/Klozz/Yuki-clang/archive/refs/heads/master.tar.gz"
             tar -C $HOME/tc --strip-components=1 -zxf weebx.tar.gz && rm weebx.tar.gz
             rm -rf $HOME/tc/bin/ld* $HOME/tc/bin/as*

         elif [ "${{ inputs.compiler }}" = "zycromer-clang" ]; then
             echo "Downloading Verified ZyCromerZ Clang Stable Build..."
             aria2c -q -o zycromer.tar.gz "https://github.com/ZyCromerZ/Clang/releases/download/Clang-16.0.6-20260510-release/Clang-16.0.6-20260510-release.tar.gz"
             tar -C $HOME/tc --strip-components=1 -zxf zycromer.tar.gz && rm zycromer.tar.gz
             rm -rf $HOME/tc/bin/ld* $HOME/tc/bin/as*

         elif [ "${{ inputs.compiler }}" = "sdclang" ]; then
             echo "Cloning Snapdragon LLVM Compiler (SDClang)..."
             git clone --depth=1 https://github.com/WeeAris/SDClang.git $HOME/tc
         fi

    - name: Clone Kernel Source
      run: git clone --depth=1 ${{ inputs.kernel-url }} -b ${{ inputs.kernel-branch }} kernel-dir

    - name: Pro Configuration Engine
      run: |
         cd kernel-dir
         
         # 1. Logika Versi Kernel (Makefile)
         if [ "${{ inputs.kernel_version }}" != "original" ] && [ "${{ inputs.kernel_version }}" != "" ]; then
             echo "Manually setting kernel version to: ${{ inputs.kernel_version }}"
             sed -i "s/^VERSION =.*/VERSION = $(echo ${{ inputs.kernel_version }} | cut -d. -f1)/" Makefile
             sed -i "s/^PATCHLEVEL =.*/PATCHLEVEL = $(echo ${{ inputs.kernel_version }} | cut -d. -f2)/" Makefile
             sed -i "s/^SUBLEVEL =.*/SUBLEVEL = $(echo ${{ inputs.kernel_version }} | cut -d. -f3)/" Makefile
         fi
         
         # 2. Branding Localversion
         sed -i 's/CONFIG_LOCALVERSION=.*/CONFIG_LOCALVERSION=" ${{ inputs.kernel_name }}-${{ inputs.rom_type }}"/g' arch/arm64/configs/${{ inputs.kernel-config }}
         
         # 3. Clean Versioning (No '+' or '-dirty')
         touch .scmversion
         export LOCALVERSION=""
         
         # 4. APatch Support Fix (Kallsyms & Kprobes)
         echo "CONFIG_KALLSYMS=y" >> arch/arm64/configs/${{ inputs.kernel-config }}
         echo "CONFIG_KALLSYMS_ALL=y" >> arch/arm64/configs/${{ inputs.kernel-config }}
         echo "CONFIG_KPROBES=y" >> arch/arm64/configs/${{ inputs.kernel-config }}
         echo "CONFIG_HAVE_KPROBES=y" >> arch/arm64/configs/${{ inputs.kernel-config }}
         
         # 5. Disable LTO Logic
         if [ "${{ inputs.disable-lto }}" = "true" ]; then
             sed -i 's/CONFIG_LTO=y/CONFIG_LTO=n/' arch/arm64/configs/${{ inputs.kernel-config }} || true
             sed -i 's/CONFIG_LTO_CLANG=y/CONFIG_LTO_CLANG=n/' arch/arm64/configs/${{ inputs.kernel-config }} || true
             echo "CONFIG_LTO_NONE=y" >> arch/arm64/configs/${{ inputs.kernel-config }}
         fi

         # 6. Injection Mesin Frekuensi GPU Custom (Overclock / Downclock)
         echo "Mengonfigurasi Frekuensi GPU..."
         MIN_HZ=$((${{ inputs.gpu_min_clock }} * 1000000))
         MAX_HZ=$((${{ inputs.gpu_max_clock }} * 1000000))
         TARGET_DTSI="arch/arm64/boot/dts/qcom/sdm845-gpu.dtsi"
         if [ -f "$TARGET_DTSI" ]; then
             sed -i "/qcom,gpu-pwrlevel@0/,/qcom,gpu-pwrlevel/s/qcom,gpu-freq = <.*>;/qcom,gpu-freq = <$MAX_HZ>;/g" $TARGET_DTSI || true
             sed -i "/qcom,gpu-pwrlevel@6/,/qcom,gpu-pwrlevel/s/qcom,gpu-freq = <.*>;/qcom,gpu-freq = <$MIN_HZ>;/g" $TARGET_DTSI || true
         else
             find arch/arm64/boot/dts/ -name "*gpu*.dtsi" -exec sed -i "s/qcom,gpu-freq = <710000000>;/qcom,gpu-freq = <$MAX_HZ>;/g" {} + || true
         fi
         
         # 7. KernelSU / KernelSU-Next
         if [ "${{ inputs.kernelsu }}" = "ksu" ]; then
            curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s v0.9.5
         elif [ "${{ inputs.kernelsu }}" = "next" ]; then
            curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -s next
         fi

    - name: Proses Kompilasi Pro
      run: |
         cd kernel-dir
         export PATH=$HOME/tc/bin:$HOME/gcc-64/bin:$HOME/gcc-32/bin:$PATH
         
         # Branding Host/User (@project-labs)
         export KBUILD_BUILD_USER="${{ inputs.project_name }}"
         export KBUILD_BUILD_HOST="project-labs"
         
         # Proteksi Khusus Pipa Rusak (Broken Pipe) pada AOSP / SDClang
         if [ "${{ inputs.compiler }}" = "aosp-clang" ] || [ "${{ inputs.compiler }}" = "sdclang" ]; then
             echo "Menggunakan Standar AOSP/SDClang: Mematikan LLVM_IAS..."
             USE_IAS=0
         else
             echo "Menggunakan Custom Clang Pro: Mengaktifkan LLVM_IAS..."
             USE_IAS=1
         fi
         
         args="ARCH=arm64 O=../out \
              CC=clang \
              HOSTCC=gcc \
              HOSTCXX=g++ \
              HOSTLD=ld \
              AR=llvm-ar \
              NM=llvm-nm \
              OBJCOPY=llvm-objcopy \
              OBJDUMP=llvm-objdump \
              STRIP=aarch64-linux-android-strip \
              LLVM_IAS=$USE_IAS \
              CROSS_COMPILE=aarch64-linux-android- \
              CROSS_COMPILE_ARM32=arm-linux-androideabi- \
              CLANG_TRIPLE=aarch64-linux-gnu-"

         echo "Membentuk konfigurasi defconfig..."
         make $args ${{ inputs.kernel-config }}
         
         echo "Memulai kompilasi kernel (Log dialihkan ke build.log)..."
         make -k -j$(nproc --all) $args 2>&1 | tee build.log
         
         # Cek hasil akhir kompilasi sebelum dikemas
         if [ ! -f ../out/arch/arm64/boot/Image ] && [ ! -f ../out/arch/arm64/boot/Image.gz ] && [ ! -f ../out/arch/arm64/boot/Image.gz-dtb ]; then
             echo "===================================================="
             echo "         !!! PROSES KOMPILASI GAGAL !!!             "
             echo "===================================================="
             echo "Menampilkan 200 baris log terakhir yang berisi error:"
             echo "----------------------------------------------------"
             tail -n 200 build.log
             echo "----------------------------------------------------"
             exit 1
         fi

    - name: Smart Packaging
      run: |
          git clone --depth=1 ${{ inputs.AK3 }} AnyKernel3
          rm -rf AnyKernel3/.git AnyKernel3/.github AnyKernel3/LICENSE AnyKernel3/README.md
          
          # Inject ZIP name to AK3
          [ -f AnyKernel3/anykernel.sh ] && sed -i "s/kernel.string=.*/kernel.string=${{ inputs.zip_name }}/g" AnyKernel3/anykernel.sh || true
          
          # Copying Image
          cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/Image.gz-dtb || cp out/arch/arm64/boot/Image.gz AnyKernel3/Image.gz || cp out/arch/arm64/boot/Image AnyKernel3/Image
          [ -f out/arch/arm64/boot/dtbo.img ] && cp out/arch/arm64/boot/dtbo.img AnyKernel3/dtbo.img || true
          
          cd AnyKernel3
          zip -r9 "../${{ inputs.zip_name }}-${{ inputs.rom_type }}.zip" * -x .git README.md

    - name: Upload Final Build
      uses: actions/upload-artifact@v4
      with:
        name: "${{ inputs.zip_name }}-${{ inputs.rom_type }}-Final-3.0"
        path: "*.zip"
