name: Kernel Build (Clang 21)

on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    steps:
    # =========================
    # Checkout source
    # =========================
    - name: Checkout
      uses: actions/checkout@v4

    # =========================
    # Install dependencies
    # =========================
    - name: Setup Build Environment
      run: |
        sudo apt update
        sudo apt install -y \
          git bc bison flex libssl-dev make \
          clang lld llvm \
          gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi \
          python3

    # =========================
    # Environment variables
    # =========================
    - name: Set Env
      run: |
        echo "ARCH=arm64" >> $GITHUB_ENV
        echo "SUBARCH=arm64" >> $GITHUB_ENV
        echo "KBUILD_BUILD_USER=linex" >> $GITHUB_ENV
        echo "KBUILD_BUILD_HOST=Project" >> $GITHUB_ENV

    # =========================
    # Prepare output dir
    # =========================
    - name: Prepare Output
      run: |
        mkdir -p out

        rm -f out/.version \
              out/include/generated/compile.h \
              out/init/version.o || true

    # =========================
    # Build kernel
    # =========================
    - name: Build Kernel
      run: |
        echo "--- 🚀 Build Kernel dengan Clang 21 ---"

        make -j$(nproc --all) \
          O=out \
          ARCH=arm64 \
          beryllium_defconfig \
          CC=clang \
          LD=ld.lld \
          LLVM=1 \
          LLVM_IAS=0 \
          KCFLAGS="-fcommon -Qunused-arguments -Wno-everything" \
          CLANG_TRIPLE=aarch64-linux-gnu- \
          CROSS_COMPILE=aarch64-linux-gnu- \
          CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
          all

    # =========================
    # Check build result
    # =========================
    - name: Check Output
      run: |
        if [ -f "out/arch/arm64/boot/Image.gz-dtb" ]; then
          echo "✅ Kompilasi Berhasil!"
        else
          echo "❌ Build Gagal!"
          exit 1
        fi

    # =========================
    # Upload kernel
    # =========================
    - name: Upload Kernel
      uses: actions/upload-artifact@v4
      with:
        name: kernel-output
        path: out/arch/arm64/boot/*
