name: linext Compiler SDM845

on:
  workflow_dispatch:
    inputs:
      ubuntu:
        description: Run on
        default: ubuntu-latest
        required: true

      name:
        description: Build name
        default: sdm845-kernel
        required: true

jobs:
  build:
    runs-on: ${{ inputs.ubuntu }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Dependencies
      run: |
        sudo apt update
        sudo apt install -y git curl bc bison flex make clang llvm gcc g++ zip

    - name: Clone Kernel
      run: |
        git clone --depth=1 https://github.com/PainKiller3/android_kernel_xiaomi_sdm845.git kernel

    - name: Build Kernel
      run: |
        mkdir -p out
        cd kernel

        export ARCH=arm64
        export SUBARCH=arm64
        export KBUILD_BUILD_USER=linex
        export KBUILD_BUILD_HOST=sdm845

        make O=../out beryllium_defconfig

        make -j$(nproc) O=../out \
        CC=clang \
        CLANG_TRIPLE=aarch64-linux-gnu- \
        CROSS_COMPILE=aarch64-linux-android- \
        CROSS_COMPILE_ARM32=arm-linux-androideabi-

    - name: Upload Kernel
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}
        path: out/*
